Repository tylrs/rancid-tomatillos, pull requests merged in 2021-07, with the labels that each got.

#5 Iteration 1/components app
  src/components/app/App.js
Labels: Component

#12 Iteration 3/movie api
  src/components/app/App.js
Labels: Component, enhancement

#16 Iteration 3/select movie api
  src/components/app/App.js
Labels: API

#29 Iteration 4/refactor/add router
  package-lock.json
  package.json
  src/components/Error/Error.js
  src/components/Movie/Movie.js
  src/components/MovieCover/MovieCover.js
  src/components/app/App.js
  src/index.js
Labels: Refactoring

#31 Feature/proptypes
  package-lock.json
  package.json
  src/components/Error/Error.js
  src/components/Movie/Movie.js
  src/components/MovieBoard/MovieBoard.js
  src/components/MovieCover/MovieCover.js
  src/components/app/App.js
Labels: error handling

#62 Feature/favorite unfavorite movie
  package-lock.json
  package.json
  src/components/Movie/Movie.js
  src/components/Movie/Movie.scss
  src/components/app/App.js
  src/utilities/apiCalls.js
  src/utilities/utils.js
Labels: Component, Server

#73 Css/clean css
  public/favicon.ico
  src/components/Error/Error.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Loader/Loader.js
  src/components/Loader/Loader.scss
  src/components/Movie/Movie.js
  src/components/Movie/Movie.scss
  src/components/MovieBoard/MovieBoard.scss
  src/components/MovieCover/MovieCover.scss
  src/components/app/App.js
  src/components/app/App.scss
  src/styles/elements/_elements.scss
  src/styles/generics/_generics.scss
  src/styles/settings/_colors.scss
  src/styles/settings/_typography.scss
  src/styles/styles.scss
  src/styles/tools/_keyframes.scss
  src/styles/tools/_mixins.scss
Labels: CSS, Refactoring, bug, enhancement

#76 Remove leftover method
  src/components/app/App.js
Labels: Refactoring

#77 Add new links
  src/utilities/apiCalls.js
Labels: API, Server
